stages:
  - test
  - build
  - deploy
  
services:
  - docker:dind  

test:
  image: node:11
  stage: test

  script:
    - yarn install
    - CI=true yarn test --all --colors

build:dev:
  image: node:11
  stage: build
  
  script: 
    - yarn install
    - REACT_APP_API_URL=https://api.dev.inowas.hydro.tu-dresden.de NODE_PATH=src yarn build
    - VERSION=$(git describe --tags --always --dirty=+) && DATE=$(date +%Y-%m-%dT%H:%M:%S) && sed -i "s/@@__VERSION__@@/${VERSION}/g;s/@@__BUILT__@@/${DATE}/g" ./build/index.html

  artifacts:
    paths:
      - build/
      
  only:
    - dev

deploy:dev:staging:
  stage: deploy
  dependencies: 
    - build:dev

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get install rsync
  script:
    - ssh -p22 SSH_CREDENTIALS_STAGING_SERVER "mkdir -p /w0190139/staging.inowas.com.tmp"
    - rsync -rav -e ssh ./build SSH_CREDENTIALS_STAGING_SERVER:/w0190139/staging.inowas.com.tmp/
    - ssh -p22 user@staging.example.com "mv /w0190139/staging.inowas.com /w0190139/staging.inowas.com.old"
    - ssh -p22 user@staging.example.com "mv /w0190139/staging.inowas.com.tmp /w0190139/staging.inowas.com"
    
  only:
    - staging
    

deploy:dev:
  image: docker:latest
  stage: deploy
  dependencies: 
    - build:dev
    
  before_script:
   - docker info
   - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  
  script: 
    - docker build  -t inowas/inowas-dss-cra:dev .
    - docker push inowas/inowas-dss-cra

  only:
    - dev
    
build:prod:
  image: node:11
  stage: build
  
  script: 
    - yarn install
    - REACT_APP_API_URL=https://api.dss.inowas.hydro.tu-dresden.de NODE_PATH=src yarn build
    - VERSION=$(git describe --tags --always --dirty=+) && DATE=$(date +%Y-%m-%dT%H:%M:%S) && sed -i "s/@@__VERSION__@@/${VERSION}/g;s/@@__BUILT__@@/${DATE}/g" ./build/index.html

  artifacts:
    paths:
      - build/
      
  only:
    - master
    
deploy:prod:
  image: docker:latest
  stage: deploy
  dependencies: 
    - build:dev
    
  before_script:
   - docker info
   - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  
  script: 
    - docker build  -t inowas/inowas-dss-cra:prod .
    - docker push inowas/inowas-dss-cra

  only:
    - master