stages:
  - test
  - build
  - deploy
  
services:
  - docker:dind  

test:
  image: node:11
  stage: test

  script:
    - yarn install
    - CI=true yarn test --all --colors

build:dev:
  image: node:11
  stage: build
  
  script: 
    - yarn install
    - REACT_APP_API_URL=https://api.dev.inowas.hydro.tu-dresden.de NODE_PATH=src yarn build
    - VERSION=$(git describe --tags --always --dirty=+) && DATE=$(date +%Y-%m-%dT%H:%M:%S) && sed -i "s/@@__VERSION__@@/${VERSION}/g;s/@@__BUILT__@@/${DATE}/g" ./build/index.html

  artifacts:
    paths:
      - build/
      
  only:
    - dev
    - staging

deploy:dev:staging:
  stage: deploy
  dependencies: 
    - build:dev

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get install rsync -y
  script:
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "mkdir -p $STAGING_PATH.tmp/"
    - rsync -rav -e ssh ./build/ $SSH_CREDENTIALS_STAGING_SERVER:/$STAGING_PATH.tmp/
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "mv $STAGING_PATH $STAGING_PATH.old"
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "mv $STAGING_PATH.tmp $STAGING_PATH"
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "rm -rf $STAGING_PATH.old"
  environment:
    name: staging
    url: https://staging.rabbl.de
  only:
    - staging

deploy:dev:production:
  stage: deploy
  dependencies: 
    - build:dev

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get install rsync -y
  script:
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "mkdir -p $PRODUCTION_PATH.tmp/"
    - rsync -rav -e ssh ./build/ $SSH_CREDENTIALS_PRODUCTION_SERVER:/$PRODUCTION_PATH.tmp/
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "mv $PRODUCTION_PATH $PRODUCTION_PATH.old"
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "mv $PRODUCTION_PATH.tmp $PRODUCTION_PATH"
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "rm -rf $PRODUCTION_PATH.old"
  environment:
    name: production
    url: https://production.rabbl.de    
  when: manual    
  only:
    - staging    

deploy:dev:
  image: docker:latest
  stage: deploy
  dependencies: 
    - build:dev
    
  before_script:
   - docker info
   - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  
  script: 
    - docker build  -t inowas/inowas-dss-cra:dev .
    - docker push inowas/inowas-dss-cra

  only:
    - dev
    
build:prod:
  image: node:11
  stage: build
  
  script: 
    - yarn install
    - REACT_APP_API_URL=https://api.dss.inowas.hydro.tu-dresden.de NODE_PATH=src yarn build
    - VERSION=$(git describe --tags --always --dirty=+) && DATE=$(date +%Y-%m-%dT%H:%M:%S) && sed -i "s/@@__VERSION__@@/${VERSION}/g;s/@@__BUILT__@@/${DATE}/g" ./build/index.html

  artifacts:
    paths:
      - build/
      
  only:
    - master
    
deploy:prod:
  image: docker:latest
  stage: deploy
  dependencies: 
    - build:dev
    
  before_script:
   - docker info
   - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  
  script: 
    - docker build  -t inowas/inowas-dss-cra:prod .
    - docker push inowas/inowas-dss-cra

  only:
    - master