stages:
  - test
  - build
  - deploy
  
services:
  - docker:dind  

test:
  image: node:11
  stage: test

  script:
    - yarn install
    - CI=true yarn test --all --colors

build:dev:
  image: node:11
  stage: build
  
  script: 
    - yarn install
    - REACT_APP_API_URL=https://api.dev.inowas.hydro.tu-dresden.de NODE_PATH=src yarn build
    - VERSION=$(git describe --tags --always --dirty=+) && DATE=$(date +%Y-%m-%dT%H:%M:%S) && sed -i "s/@@__VERSION__@@/${VERSION}/g;s/@@__BUILT__@@/${DATE}/g" ./build/index.html

  artifacts:
    paths:
      - build/
      
  only:
    - dev
    
deploy:dev:
  image: docker:latest
  stage: deploy
  dependencies: 
    - build:dev
    
  before_script:
   - docker info
   - docker login -u rabbl -p ululate-feaze-shrill
  
  script: 
    - docker build  -t inowas/inowas-dss-cra:dev .
    - docker push inowas/inowas-dss-cra

  only:
    - dev
    
build:prod:
  image: node:11
  stage: build
  
  script: 
    - yarn install
    - REACT_APP_API_URL=https://api.dss.inowas.hydro.tu-dresden.de NODE_PATH=src yarn build
    - VERSION=$(git describe --tags --always --dirty=+) && DATE=$(date +%Y-%m-%dT%H:%M:%S) && sed -i "s/@@__VERSION__@@/${VERSION}/g;s/@@__BUILT__@@/${DATE}/g" ./build/index.html

  artifacts:
    paths:
      - build/
      
  only:
    - master
    
deploy:prod:
  image: docker:latest
  stage: deploy
  dependencies: 
    - build:dev
    
  before_script:
   - docker info
   - docker login -u rabbl -p ululate-feaze-shrill
  
  script: 
    - docker build  -t inowas/inowas-dss-cra:prod .
    - docker push inowas/inowas-dss-cra

  only:
    - master